[project]
name = "triposg"
version = "0.0.1"
requires-python = ">= 3.10"

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# Map the project root ("") to your custom source location
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = [ "I",  "UP", "SIM", "RUF", "B" ]